[project]
name = "mermaid-workflow-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.10.1",
    "numpy>=2.3.1",
    "pillow>=11.2.1",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
]
